apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: {myapp:tag}
          env:
            - name: PORT
              value: "4444"
          ports:
            - containerPort: 4444
              name: myapp
